apiVersion: apps/v1
kind: Deployment
metadata:
  name: central
  labels:
    app: central
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central
  template:
    metadata:
      labels:
        app: central
    spec:
      containers:
      - name: central
        image: game-server/central:latest
        imagePullPolicy: IfNotPresent # For local testing
        ports:
        - containerPort: 9003
        env:
        - name: APP_ENV
          value: "local_k8s"
        - name: REDIS_ADDR
          value: "redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: central
spec:
  ports:
  - port: 9003
    targetPort: 9003
  selector:
    app: central
